#include"header.cpp"
//Function defination
void ab1()
{  clrscr();
   cout<<"1-D array"<<"\nThe simplest form of an array is a single dimensional array."<<endl;
   cout<<"The array is given a name and its elements are refered to by subscripts "<<endl;
   cout<<"or indices.\nThe general form of an array declaration is as follows:"<<endl;
   cout<<"type array_name[sze];"<<"\nint marks[50];"<<"\n\nPress any button to go back";
}
  //End of function defination