#include"header.cpp"
//Function defination
void ab2()//Function header
{  clrscr();
   cout<<"2-D array"<<"\nTwo dimensional array is one in which each element is itself an array."
   <<"\n2-D arrays are stored in memory in a row-column matrix."
   <<"\nThey are stored in contiguous memory locations."
   <<"\nThe total no. of bytes required to store a 2-d array are calculated as:-"
   <<"\nno. of rows(first index)x number of columns(second index) x size of(base type);"
   <<"\n\nPress any button to go back";
}
  //End of function defination