#include"header.cpp"
void main()
{ clrscr();
 int a,bj=0,co=0;
 do{clrscr();cout<<"\nVOTE";
    cout<<"\n1.BJP"<<"\n2.Congress";
    cout<<"\nEnter your choice:";cin>>a;getch();
    //if (a>=1&&a<=17){cout<<n5++<<"Not eligable to vote!!!";}
    if(a==1){bj++;}
   else if(a==2){co++;}}while(a!=0);
   cout<<"\nBJP:"<<bj;
   cout<<"\nCongress:"<<co;
   /*cout<<"\nAge between(31-50):"<<n2;
   cout<<"\nAge between(51-80):"<<n3;
   cout<<"\nAge between(above 80):"<<n4;*/getch();}
